os: linux
dist: xenial
language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npx netlify build
  - npx netlify deploy --alias $TRAVIS_JOB_ID
  - npx cypress run --env host=$TRAVIS_JOB_ID--danmatthew.netlify.app --headless
deploy:
  skip_cleanup: true
  provider: script
  script: npx netlify deploy --prod
  on:
    branch: main
