os: linux
dist: xenial
language: node_js
node_js:
  - "node"
cache: npm
script:
  - npx netlify build
deploy:
  skip_cleanup: true
  provider: script
  script: npx netlify deploy
  on:
    branch: main
