exclude:		['node_modules', '.sass-cache']

# Dependencies
# markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Matthew
tagline:          'HTML, CSS, and JavaScript developer'
description:      'Notes on modern web development with HTML, CSS, and JavaScript.'
url:              http://danmatthew.co.uk

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          1.0.0

github:
  url:           https://github.com/danielmatthew

twitter:
  url:			http://twitter.com/danielm

treehouse:
  url:			http://teamtreehouse.com/danielmatthew

updated: '04032014'