[build]
  command = "npm run production"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' res.cloudinary.com lux.speedcurve.com;
      script-src 'self' 'unsafe-inline' cdn.speedcurve.com lux.speedcurve.com unpkg.com identity.netlify.com;
      style-src 'self' 'unsafe-inline' *.cloudfront.net fonts.googleapis.com;
      font-src 'self' *.cloudfront.net fonts.gstatic.com"""

[[headers]]
  for = "/admin*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      style-src * 'unsafe-inline';
      img-src *;
      script-src * 'unsafe-eval';
      font-src *"""

[[redirects]]
  from = "/:year/:month/:date/:slug"
  to = "/notes/:slug"
  status = 301

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"

[[plugins]]
package = "netlify-plugin-hashfiles"


