[build]
  command = "npm run production"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src 'self' res.cloudinary.com; script-src 'self' 'unsafe-inline' cdn.speedcurve.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src fonts.gstatic.com"
